### ISSUE TITLE
Master ToDo list

### ISSUE THREAD

**Issue by synctext** [dicg2020/dicg2020.github.io#1]
From others we heard the key problem is getting paper submissions, given this is Covid time and a first workshop. Personal contact with your social circle early on is key. _This needs to be done in June for the deadline 60 days later._

- [x] publish website
  - [X] Arrange Github matters
  - [x] Publish a early version marked **draft**
  - [x] finalize cfp deadlines etc.
<img src="https://user-images.githubusercontent.com/325224/84992570-60527600-b148-11ea-8af1-f67b73a383bb.png" width=200>

- [ ] Program Committee
  - [ ] copy candidates to reach out from from other distributed systems conferences (long list)
  - [ ] personally connect to the field key people(e.g. Maarten van Steen, Seif Haridi, Prateek Mittal Princeton, etc.)
  - [ ] ask (_beg_) them to submit student papers
  - [ ] Will we also personally invite https://www.surrey.ac.uk/people/nigel-gilbert and https://www.ifi.uzh.ch/en/ce/people/seuken.html people from somewhat adjacent fields.
- [ ] Event organisation
  - [ ] they try to meet in-person at Delft, if laws permit.
  - [ ] Make another grand ToDo list (@cuileri @llegard)

**Comment by llegard** [comment]
What is the latest viable date for submission deadlines? We should pick those, given the difficulties.

**Comment by cuileri** [comment]
Middleware requires that the camera-ready versions should be available by 16th of October. I picked the other deadlines myself, considering a possible one or two-week extension.

**Comment by synctext** [comment]
We might need to work with tighter deadline and leave no room for a deadline extension (if camera-ready by main conference does not shift).

Middleware main conference Notification: Friday, August 28, 2020
Thus rejected papers there will possible end up in workshops, if they fit or even if they don't fit.
10 days for Camera ready and 2 weeks review period? (all-hands on deck time..)

**Comment by cuileri** [comment]
Paper submissions: September 21, 2020 (AOE)
Notification of acceptance: October 5, 2020 (AOE)
Camera ready version: October 15, 2020

**Comment by cuileri** [comment]
Web page is in a good shape now. No need to refer to it as "draft". We wrote "TBD" in program committee anyway.

We can share the link but please be aware that whatever we write here is visible to others as long as the website is public. The solution is to upgrade to PRO ($4/month).
